### ISSUE TITLE
Max & Min buttons ought to be removed.

### ISSUE THREAD

**Issue by NeilHDerby** [raspberrypi-ui/pishutdown#8]
Both the Max & Min buttons are pointless on this 'Shutdown Options' window. Currently the Max button does nothing!

Why not suppress the display of both buttons by adding:

`gtk_window_set_type_hint(GTK_WINDOW (dlg), GDK_WINDOW_TYPE_HINT_MENU);`

just after instantiating the window at line 98.

**Comment by spl237** [comment]
Because the design of windows should be consistent unless there is a very good reason for them not to be. This dialog can be minimised to the taskbar, just like any other. It can't be maximised, so the maximise option is greyed but still shown, as on other windows for which this is the case. All removing the buttons would do is to make the window inconsistent with other windows.
